"""V5 Thinking pre-answer power extension -- analysis (SEALED PROTOCOL).

Within-Thinking analysis of the powered replication cohort (hash-pool offsets
>= 1500, generated by bg_v5_thinking_power_generate.py with the sealed v3
Thinking generator protocol unmodified: k=4, max_new=448, T=0.7, top_p=0.95,
seed 20260724, strict pre-answer cut, deterministic split_for splits).

SEALED ENDPOINTS AND VERDICTS (written before any v5 generation):
  Stage A (gate): reproduce the pilot's published increments (both the 4- and
    5-shortcut arms of thinking_preanswer_results.json, and the preserved
    per-candidate held-out scores) to 1e-9 from the preserved pilot artifacts
    BEFORE touching any new data. Abort on any mismatch.
  PRIMARY: new-only cohort (tasks at offsets >= 1500, disjoint from all prior
    slices), incremental AUROC (combined - shortcut) under the adversarial
    5-shortcut composite (incl. malformed-sibling count), fit on new train+val,
    evaluated on new heldout; paired task-clustered bootstrap, 2000 rounds,
    seed 20260727; 95% CI, plus 90% CI for TOST at +/-0.05.
  SECONDARY: pooled with the pilot -- labelled 'pooled precision estimate --
    NOT independent replication'.
  Sealed malformedness controls: (a) drop-tasks-with->=75%-malformed control
    arm on the primary held-out scores; (b) hidden-only malformedness-
    prediction AUROC diagnostic on the new held-out records.
  VERDICT (checked strictly in this order, on the PRIMARY point estimate and
  seed-20260727 intervals):
    NEGATIVE_TRANSFER        if 95% upper < 0
    POSITIVE_REPLICATION     if 95% lower > 0   (flag PRACTICALLY_SMALL=true
                             if point estimate < 0.05 or the equivalence
                             condition also holds)
    PRACTICAL_EQUIVALENCE    if 90% CI entirely within [-0.05, +0.05]
    UNRESOLVED               otherwise (incl. insufficient-data conditions,
                             reported with counts, not massaged)
  No stopping rules, no budget changes: this analysis runs ONCE on whatever
  the generator produced.

Writes thinking_power_results.json (+ raw_predictions_heldout_v5.json) into
artifacts/reports/thinking_preanswer_power_v5_20260727/. Read-only w.r.t. all
prior artifact roots. --stage-a-only runs the gate alone (CPU smoke).
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
from pathlib import Path

import torch

PROJECT_ROOT = Path(__file__).resolve().parents[3]
MANUAL = PROJECT_ROOT / "utilities/tests/manual"
for p in (str(PROJECT_ROOT), str(MANUAL)):
    if p not in sys.path:
        sys.path.insert(0, p)

from proto_introspection_controls_analysis import auroc  # noqa: E402
from bg_v2_overnight_horizon_analysis import (  # noqa: E402
    shortcut_vec, select_hparams, cv_auroc,
)
from bg_v2_overnight_horizon_generate import split_for  # noqa: E402
from bg_v2_malformed_sibling_control import shortcut_vec_aug, malformed_count_by_task  # noqa: E402
from bg_v3_horizon_power_analysis import load_records, run_arm  # noqa: E402

PILOT_ROOT = PROJECT_ROOT / "artifacts/reports/thinking_preanswer_v3_20260726"
PILOT_SHARDS = PILOT_ROOT / "horizon_logic"
OUT_ROOT = PROJECT_ROOT / "artifacts/reports/thinking_preanswer_power_v5_20260727"
V5_SHARDS = OUT_ROOT / "horizon_logic"

GATE_TOL = 1e-9
BOOT_SEED = 20260727
BOOT_ROUNDS = 2000
MIN_NEW_OFFSET = 1500        # ledger: [0,1500) consumed by v2/v3/C2/C3/C4/C5 slices
PRACTICAL_MARGIN = 0.05      # TOST / equivalence margin
SMALL_POINT = 0.05           # PRACTICALLY_SMALL point-estimate threshold
HIGH_MALFORMED_SHARE = 0.75  # control-arm task-drop threshold (as published)


def bootstrap_task_clustered_dual(scores_a, scores_b, y, task_uids,
                                  rounds=BOOT_ROUNDS, seed=BOOT_SEED):
    """Verbatim reference loop of bg_v2_overnight_horizon_analysis
    .bootstrap_task_clustered (same RNG consumption, skip rules and quantile
    convention), with a 90% interval read from the same sorted deltas."""
    import math
    rng = torch.Generator().manual_seed(seed)
    uniq = sorted(set(task_uids))
    by_task: dict = {}
    for i, t in enumerate(task_uids):
        by_task.setdefault(t, []).append(i)
    deltas = []
    for _ in range(rounds):
        pick = torch.randint(0, len(uniq), (len(uniq),), generator=rng).tolist()
        idxs = []
        for pi in pick:
            idxs.extend(by_task[uniq[pi]])
        if not idxs:
            continue
        idx_t = torch.tensor(idxs)
        yb = y[idx_t]
        if yb.float().mean() in (0.0, 1.0):
            continue
        aa = auroc(scores_a[idx_t], yb)
        bb = auroc(scores_b[idx_t], yb)
        if math.isnan(aa) or math.isnan(bb):
            continue
        deltas.append(aa - bb)
    if not deltas:
        return None
    deltas.sort()
    n = len(deltas)
    return {
        "n_rounds_used": n,
        "seed": seed,
        "mean_delta": sum(deltas) / n,
        "ci95": [deltas[int(0.025 * n)], deltas[int(0.975 * n)]],
        "ci90": [deltas[int(0.05 * n)], deltas[int(0.95 * n)]],
        "excludes_zero_95": bool(deltas[int(0.025 * n)] > 0 or deltas[int(0.975 * n)] < 0),
    }


def decide_verdict(point, ci95, ci90,
                   margin=PRACTICAL_MARGIN, small_point=SMALL_POINT):
    """Sealed verdict logic, checked strictly in this order."""
    lo95, hi95 = ci95
    lo90, hi90 = ci90
    equivalence = (lo90 >= -margin) and (hi90 <= margin)
    flags = {"PRACTICALLY_SMALL": False, "equivalence_condition_held": bool(equivalence)}
    if hi95 < 0:
        return "NEGATIVE_TRANSFER", flags
    if lo95 > 0:
        flags["PRACTICALLY_SMALL"] = bool(point < small_point or equivalence)
        return "POSITIVE_REPLICATION", flags
    if equivalence:
        return "PRACTICAL_EQUIVALENCE", flags
    return "UNRESOLVED", flags


def stage_a_gate():
    """Reproduce the pilot's published numbers to 1e-9 from preserved artifacts."""
    pilot = load_records(PILOT_SHARDS)
    if not pilot:
        raise SystemExit("STAGE A: no preserved pilot shards found")
    published = json.loads((PILOT_ROOT / "thinking_preanswer_results.json").read_text())
    raw = json.loads((PILOT_ROOT / "raw_predictions_heldout.json").read_text())
    mal = malformed_count_by_task(pilot)
    print(f"[v5-power] STAGE A: {len(pilot)} preserved pilot records "
          f"({published['n_candidates']} published)", flush=True)

    report = {}
    ok = True
    for arm_name, sc_fn, key in (
            ("gate_pilot_4sc", shortcut_vec, "arm_4sc"),
            ("gate_pilot_5sc", lambda r: shortcut_vec_aug(r, mal), "arm_5sc")):
        got, preds = run_arm(arm_name, pilot, sc_fn)
        pub = published[key]
        pb = pub["paired_task_clustered_bootstrap_combined_minus_shortcut"]
        gb = got["paired_task_clustered_bootstrap_combined_minus_shortcut"]
        checks = [
            ("auroc_shortcut_only", got["auroc_shortcut_only"], pub["auroc_shortcut_only"]),
            ("auroc_hidden_only", got["auroc_hidden_only"], pub["auroc_hidden_only"]),
            ("auroc_combined", got["auroc_hidden_plus_shortcuts"],
             pub["auroc_hidden_plus_shortcuts"]),
            ("incremental", got["incremental_auroc_combined_minus_shortcut"],
             pub["incremental_auroc_combined_minus_shortcut"]),
            ("boot_mean", gb["mean_delta"], pb["mean_delta"]),
            ("boot_ci_lo", gb["ci95"][0], pb["ci95"][0]),
            ("boot_ci_hi", gb["ci95"][1], pb["ci95"][1]),
        ]
        arm_rep = {}
        for label, mine, theirs in checks:
            d = abs(mine - theirs)
            arm_rep[label] = {"reproduced": mine, "published": theirs,
                              "abs_diff": d, "match": bool(d <= GATE_TOL)}
            flag = "OK " if d <= GATE_TOL else "FAIL"
            print(f"[v5-power]   [{flag}] {key}/{label}: |d|={d:.3e}", flush=True)
            ok = ok and d <= GATE_TOL
        # preserved per-candidate held-out scores
        for stream in ("hidden", "shortcut", "combined"):
            md = max(abs(a - b) for a, b in zip(raw[key]["scores"][stream],
                                                preds["scores"][stream]))
            arm_rep[f"scores_{stream}_max_abs_diff"] = md
            flag = "OK " if md <= GATE_TOL else "FAIL"
            print(f"[v5-power]   [{flag}] {key}/scores_{stream}: max|d|={md:.3e}", flush=True)
            ok = ok and md <= GATE_TOL
        assert raw[key]["tasks"] == preds["tasks"], f"{key}: held-out task order drifted"
        assert raw[key]["y"] == preds["y"], f"{key}: held-out labels drifted"
        report[key] = arm_rep

    if not ok:
        OUT_ROOT.mkdir(parents=True, exist_ok=True)
        (OUT_ROOT / "STAGE_A_GATE_FAILED.json").write_text(
            json.dumps(report, indent=2, default=str) + "\n")
        raise SystemExit("STAGE A GATE FAILED: pilot numbers not reproduced to 1e-9 -- "
                         "refusing to touch new data")
    print("[v5-power] STAGE A GATE PASSED: pilot published numbers reproduced to 1e-9",
          flush=True)
    return pilot, report


def load_new_records():
    records, offsets = [], []
    for path in sorted(glob.glob(str(V5_SHARDS / "horizon_generation_*.pt"))):
        payload = torch.load(path, map_location="cpu", weights_only=False)
        off = payload.get("task_offset", -1)
        assert off >= MIN_NEW_OFFSET, (
            f"shard {path} has task_offset={off} < {MIN_NEW_OFFSET}: overlaps prior slices")
        offsets.append(off)
        records.extend(payload["records"])
    return records, offsets


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage-a-only", action="store_true",
                    help="run the pilot reproduction gate only (CPU smoke); no writes")
    args = ap.parse_args()

    pilot, gate_report = stage_a_gate()
    if args.stage_a_only:
        print("[v5-power] --stage-a-only: gate passed, exiting without touching new data",
              flush=True)
        return

    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    new, offsets = load_new_records()
    if not new:
        raise SystemExit("no v5 shards found -- run bg_v5_thinking_power_generate.py first")
    print(f"[v5-power] new records={len(new)} from shard offsets {sorted(offsets)}", flush=True)

    # ---- cohort integrity (prospective, deterministic) ----------------------
    pilot_tasks = {r["task_uid"] for r in pilot}
    new_tasks = {r["task_uid"] for r in new}
    overlap = pilot_tasks & new_tasks
    assert not overlap, f"task overlap with pilot: {sorted(overlap)[:5]}"
    bad_split = [r["task_uid"] for r in new if r["split"] != split_for(r["task_uid"])]
    assert not bad_split, f"split mismatch vs deterministic split_for: {bad_split[:5]}"
    per_task_n: dict = {}
    for r in new:
        per_task_n[r["task_uid"]] = per_task_n.get(r["task_uid"], 0) + 1
    assert set(per_task_n.values()) == {4}, (
        f"non-uniform k per task: {sorted(set(per_task_n.values()))}")
    print(f"[v5-power] cohort gate OK: {len(new_tasks)} new tasks, disjoint from pilot, "
          "splits reproduce split_for, k=4 uniform", flush=True)

    n_mal = sum(r["malformed"] for r in new)
    scor = [r for r in new if not r["malformed"]]
    ho = [r for r in scor if r["split"] == "heldout"]
    tv = [r for r in scor if r["split"] in ("train", "val")]
    results = {
        "protocol": ("sealed v3 Thinking generator protocol; analysis machinery identical to "
                     "bg_v3_thinking_preanswer_analysis (fit family, grouped CV, grid, split, "
                     "adversarial 5-shortcut composite); primary bootstrap seed 20260727"),
        "bootstrap_seed": BOOT_SEED,
        "min_new_offset": MIN_NEW_OFFSET,
        "stage_a_gate": "PASSED",
        "stage_a_report": gate_report,
        "n_candidates": len(new),
        "n_tasks": len(new_tasks),
        "n_malformed": n_mal,
        "malformed_rate": n_mal / len(new),
        "n_scorable": len(scor),
        "n_trainval_scorable": len(tv),
        "n_heldout_scorable": len(ho),
        "n_heldout_negatives": sum(1 for r in ho if not r["success"]),
        "pilot_reference_malformed_rate": sum(r["malformed"] for r in pilot) / len(pilot),
    }

    single_class = (len({bool(r["success"]) for r in ho}) < 2)
    if len(tv) < 20 or len(ho) < 20 or single_class:
        results["verdict"] = "UNRESOLVED"
        results["flags"] = {"PRACTICALLY_SMALL": False, "equivalence_condition_held": False}
        results["unresolved_reason"] = ("insufficient data: trainval_scorable="
                                        f"{len(tv)}, heldout_scorable={len(ho)}, "
                                        f"single_class_heldout={single_class}")
        (OUT_ROOT / "thinking_power_results.json").write_text(
            json.dumps(results, indent=2, default=str) + "\n")
        print(f"[v5-power] VERDICT: UNRESOLVED ({results['unresolved_reason']})", flush=True)
        return

    # ---- PRIMARY: new-only, adversarial 5-shortcut composite -----------------
    mal_new = malformed_count_by_task(new)
    arm_new, preds_new = run_arm("v5_new_only_5sc", new, lambda r: shortcut_vec_aug(r, mal_new))
    s_comb = torch.tensor(preds_new["scores"]["combined"], dtype=torch.float64)
    s_sc = torch.tensor(preds_new["scores"]["shortcut"], dtype=torch.float64)
    y_ho = torch.tensor(preds_new["y"], dtype=torch.float32)
    tasks_ho = preds_new["tasks"]
    boot_new = bootstrap_task_clustered_dual(s_comb, s_sc, y_ho, tasks_ho)
    point = arm_new["incremental_auroc_combined_minus_shortcut"]
    results["primary_new_only_5sc"] = arm_new
    results["primary_bootstrap_seed20260727"] = boot_new
    print(f"[v5-power] PRIMARY new-only 5sc: point {point:+.4f} "
          f"ci95 [{boot_new['ci95'][0]:+.4f}, {boot_new['ci95'][1]:+.4f}] "
          f"ci90 [{boot_new['ci90'][0]:+.4f}, {boot_new['ci90'][1]:+.4f}]", flush=True)

    # ---- SECONDARY: pooled precision estimate --------------------------------
    pooled = pilot + new
    mal_pool = malformed_count_by_task(pooled)
    arm_pool, preds_pool = run_arm("v5_pooled_5sc", pooled,
                                   lambda r: shortcut_vec_aug(r, mal_pool))
    boot_pool = bootstrap_task_clustered_dual(
        torch.tensor(preds_pool["scores"]["combined"], dtype=torch.float64),
        torch.tensor(preds_pool["scores"]["shortcut"], dtype=torch.float64),
        torch.tensor(preds_pool["y"], dtype=torch.float32), preds_pool["tasks"])
    results["secondary_pooled_5sc"] = {
        "label": "pooled precision estimate -- NOT independent replication",
        "arm": arm_pool,
        "bootstrap_seed20260727": boot_pool,
    }
    print(f"[v5-power] SECONDARY pooled 5sc: point "
          f"{arm_pool['incremental_auroc_combined_minus_shortcut']:+.4f} "
          f"ci95 [{boot_pool['ci95'][0]:+.4f}, {boot_pool['ci95'][1]:+.4f}] "
          "(pooled precision estimate -- NOT independent replication)", flush=True)

    # ---- sealed malformedness controls ---------------------------------------
    controls: dict = {}
    # (a) drop tasks with >= 75% malformed candidates, recheck primary increment
    mal_share: dict = {}
    for r in new:
        mal_share.setdefault(r["task_uid"], []).append(bool(r["malformed"]))
    heavy = {t for t, ms in mal_share.items() if sum(ms) / len(ms) >= HIGH_MALFORMED_SHARE}
    keep = torch.tensor([t not in heavy for t in tasks_ho])
    if int(keep.sum()) >= 10 and float(y_ho[keep].float().mean()) not in (0.0, 1.0):
        inc_drop = auroc(s_comb[keep], y_ho[keep]) - auroc(s_sc[keep], y_ho[keep])
        boot_drop = bootstrap_task_clustered_dual(
            s_comb[keep], s_sc[keep], y_ho[keep],
            [t for t, k in zip(tasks_ho, keep.tolist()) if k])
        controls["drop_high_malformed_tasks"] = {
            "threshold": HIGH_MALFORMED_SHARE,
            "n_heldout_tasks_dropped": len(heavy & set(tasks_ho)),
            "n_candidates_remaining": int(keep.sum()),
            "incremental": inc_drop,
            "bootstrap_seed20260727": boot_drop,
        }
        print(f"[v5-power] control drop>=75%-malformed tasks: increment {inc_drop:+.4f} "
              f"(dropped {controls['drop_high_malformed_tasks']['n_heldout_tasks_dropped']} "
              "held-out tasks)", flush=True)
    else:
        controls["drop_high_malformed_tasks"] = {
            "note": "too few candidates remaining after drop, or single-class subset"}
        print("[v5-power] control drop>=75%-malformed tasks: not computable", flush=True)

    # (b) hidden-only malformedness-prediction AUROC diagnostic (held-out only)
    ho_all = [r for r in new if r["split"] == "heldout"]
    y_mal = torch.tensor([1.0 if r["malformed"] else 0.0 for r in ho_all])
    if float(y_mal.float().mean()) not in (0.0, 1.0):
        Xhid_mal = torch.stack([r["preanswer_features"].flatten().float() for r in ho_all])
        tasks_mal = [r["task_uid"] for r in ho_all]
        best_mal = select_hparams(Xhid_mal, y_mal, tasks_mal)
        oof = cv_auroc(Xhid_mal, y_mal, tasks_mal, best_mal[1], best_mal[2])
        controls["malformed_vs_clean_hidden_auroc"] = auroc(oof, y_mal)
    else:
        controls["malformed_vs_clean_hidden_auroc"] = None
    controls["malformed_vs_clean_note"] = (
        "hidden-state grouped-CV AUROC for predicting malformed(1)/clean(0) on the new "
        "held-out records -- a DIFFERENT label than correctness; reported so a reader can "
        "check the correctness increment is not this signal in disguise")
    print(f"[v5-power] control malformed-vs-clean hidden AUROC: "
          f"{controls['malformed_vs_clean_hidden_auroc']}", flush=True)
    results["controls"] = controls

    # ---- VERDICT --------------------------------------------------------------
    verdict, flags = decide_verdict(point, boot_new["ci95"], boot_new["ci90"])
    results["verdict"] = verdict
    results["flags"] = flags
    results["verdict_basis"] = {
        "point_estimate": point,
        "ci95": boot_new["ci95"],
        "ci90": boot_new["ci90"],
        "margin": PRACTICAL_MARGIN,
        "small_point_threshold": SMALL_POINT,
        "order": ["NEGATIVE_TRANSFER", "POSITIVE_REPLICATION",
                  "PRACTICAL_EQUIVALENCE", "UNRESOLVED"],
    }
    print(f"[v5-power] VERDICT: {verdict} flags={flags}", flush=True)

    (OUT_ROOT / "thinking_power_results.json").write_text(
        json.dumps(results, indent=2, default=str) + "\n", encoding="utf-8")
    (OUT_ROOT / "raw_predictions_heldout_v5.json").write_text(
        json.dumps({"new_only_5sc": preds_new, "pooled_5sc": preds_pool}, indent=2) + "\n",
        encoding="utf-8")
    print(f"[v5-power] wrote {OUT_ROOT / 'thinking_power_results.json'} and "
          f"{OUT_ROOT / 'raw_predictions_heldout_v5.json'}", flush=True)


if __name__ == "__main__":
    main()
