"""V3 Thinking pre-answer replication -- generation (SEALED PROTOCOL).

Runs the sealed Horizon Logic pre-answer generation protocol on the
Ouro-2.6B-Thinking checkpoint instead of RLTT. Every protocol constant is
inherited unmodified from bg_v2_overnight_horizon_generate: task pool, hash
ordering, per-task seeds, prompts, sampling (T=0.7, top_p=0.95, k=4,
max_new=448), the strict pre-answer cut, and the feature capture convention.

SEALED DESIGN DECISIONS (made before any Thinking generation was run):
  - Task slice: offsets [0, 170) -- the SAME tasks as the RLTT v2 main run,
    so the checkpoint is the only varied factor. Candidates are generated by
    Thinking itself (pre-answer success prediction is about a model's own
    computation); splits are the sealed deterministic function of task_uid.
  - max_new stays 448 despite Thinking's longer reasoning style: protocol
    identity outranks scorable-pool size, and the malformed/truncation-rate
    difference vs RLTT is itself a reported quantity. NOT to be revised after
    observing class balance.
  - Endpoint (analysis script): the WITHIN-Thinking nested increment
    (combined - shortcut) on its own heldout, under both the 4-shortcut and
    adversarial 5-shortcut composites. No cross-checkpoint AUROC comparisons.

Model: ByteDance/Ouro-2.6B-Thinking @ f1edd81e7ac41355db670500ceaf204e0f73af68
(the pinned revision already used by tools/paper_verification).
"""
from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
MANUAL = PROJECT_ROOT / "utilities/tests/manual"
for p in (str(PROJECT_ROOT), str(MANUAL)):
    if p not in sys.path:
        sys.path.insert(0, p)

import bg_v2_overnight_horizon_generate as v2gen  # noqa: E402
import src.evaluator.bg_transformer_features as feat  # noqa: E402

OUT_ROOT = PROJECT_ROOT / "artifacts/reports/thinking_preanswer_v3_20260726/horizon_logic"
# models/ouro_thinking_local = the pinned f1edd81 snapshot (weights/tokenizer/
# config symlinked, byte-identical) plus ONE compatibility shim in
# modeling_ouro.py: UniversalTransformerCache.key_cache/value_cache exposed as
# property+setter, mirroring the patch already present in ouro_rltt_local.
# Upstream's plain attributes collide with the transformers-4.54 Cache base
# class during generate(). Recorded as an infrastructure amendment in the
# sealed plan; no weight, protocol, or sampling change.
SNAP = PROJECT_ROOT / "models/ouro_thinking_local"
MAX_OFFSET_EXCL = 170   # mirror of the RLTT v2 main slice; nothing beyond it


def main() -> None:
    import argparse
    guard = argparse.ArgumentParser(add_help=False)
    guard.add_argument("--task-offset", type=int, default=0)
    guard.add_argument("--n-tasks", type=int, default=24)
    known, _ = guard.parse_known_args()
    if known.task_offset + known.n_tasks > MAX_OFFSET_EXCL:
        raise SystemExit(
            f"refusing: slice [{known.task_offset}, {known.task_offset + known.n_tasks}) "
            f"exceeds the sealed mirror slice [0, {MAX_OFFSET_EXCL})")
    assert SNAP.exists(), f"pinned Thinking snapshot missing: {SNAP}"

    base_cls = feat.BGTransformerFeatureExtractor

    class ThinkingExtractor(base_cls):
        def __init__(self, **kw):
            kw.setdefault("model_path", SNAP)
            super().__init__(**kw)

    feat.BGTransformerFeatureExtractor = ThinkingExtractor
    v2gen.OUT_ROOT = OUT_ROOT
    v2gen.main()


if __name__ == "__main__":
    main()
