"""V3 Horizon Logic power extension -- analysis.

Combines the sealed v2 main-run shards (offsets [0,170), read-only) with the
new v3 shards (offsets >= 170) generated by bg_v3_horizon_power_generate.py.

Protocol is IDENTICAL to bg_v2_overnight_horizon_analysis.py / the malformed-
sibling control: same fit family, same task-grouped CV, same hyperparameter
grid, same deterministic prospective task-level split, same seed, same
2000-round paired task-clustered bootstrap.

Stage A (gate)   : re-run the published 4-shortcut protocol on v2-only records
                   and ABORT unless it reproduces auroc_results.json to 1e-9.
Stage B (arms)   : for BOTH shortcut composites (4-feature published; 5-feature
                   including the malformed-sibling count, the adversarial
                   baseline that pushed the v2 CI across zero):
                     - new_only : fit on v3 train+val, eval on v3 heldout
                                  (independent replication on disjoint tasks)
                     - pooled   : fit on all train+val, eval on pooled heldout
Stage C (controls): task-set disjointness, zero split-crossing (split is a pure
                   function of task_uid), shuffled-label, leave-one-task-out
                   max influence on the pooled 5-shortcut increment,
                   malformed-share task-drop recheck, per-split negative counts.

Writes only into artifacts/reports/horizon_power_v3_20260726/.
"""
from __future__ import annotations

import glob
import json
import sys
from pathlib import Path

import torch

PROJECT_ROOT = Path(__file__).resolve().parents[3]
MANUAL = PROJECT_ROOT / "utilities/tests/manual"
for p in (str(PROJECT_ROOT), str(MANUAL)):
    if p not in sys.path:
        sys.path.insert(0, p)

from proto_introspection_controls_analysis import auroc  # noqa: E402
from bg_v2_overnight_horizon_analysis import (  # noqa: E402
    HORIZON_ROOT, SEED, shortcut_vec, select_hparams, fit_final, apply_final,
    bootstrap_task_clustered,
)
from bg_v2_overnight_horizon_generate import split_for  # noqa: E402
from bg_v2_malformed_sibling_control import (  # noqa: E402
    arm, shortcut_vec_aug, malformed_count_by_task,
)

V3_ROOT = PROJECT_ROOT / "artifacts/reports/horizon_power_v3_20260726/horizon_logic"
OUT_ROOT = PROJECT_ROOT / "artifacts/reports/horizon_power_v3_20260726"
GATE_TOL = 1e-9


def load_records(root: Path) -> list[dict]:
    records = []
    for path in sorted(glob.glob(str(root / "horizon_generation_*.pt"))):
        payload = torch.load(path, map_location="cpu", weights_only=False)
        records.extend(payload["records"])
    return records


def assemble(records: list[dict], sc_fn):
    """Scorable-only design matrices, mirroring the v2 analysis assembly."""
    scorable = [r for r in records if not r["malformed"]]
    Xhid = torch.stack([r["preanswer_features"].flatten().float() for r in scorable])
    Xsc = torch.stack([sc_fn(r) for r in scorable]).float()
    y = torch.tensor([1.0 if r["success"] else 0.0 for r in scorable])
    tasks = [r["task_uid"] for r in scorable]
    splits = [r["split"] for r in scorable]
    tv = torch.tensor([s in ("train", "val") for s in splits])
    ho = torch.tensor([s == "heldout" for s in splits])
    return scorable, Xhid, Xsc, y, tasks, tv, ho


def run_arm(name, recs, sc_fn):
    _, Xhid, Xsc, y, tasks, tv, ho = assemble(recs, sc_fn)
    tasks_tv = [t for t, m in zip(tasks, tv.tolist()) if m]
    tasks_ho = [t for t, m in zip(tasks, ho.tolist()) if m]
    out = arm(name, Xhid[tv], Xsc[tv], y[tv], tasks_tv, Xhid[ho], Xsc[ho], y[ho], tasks_ho)
    out["n_heldout"] = int(ho.sum())
    out["n_heldout_tasks"] = len(set(tasks_ho))
    out["n_heldout_negatives"] = int((y[ho] == 0).sum())
    out["heldout_base_rate"] = float(y[ho].mean())
    scores = out.pop("_scores")
    return out, {"tasks": tasks_ho, "y": y[ho].tolist(),
                 "scores": {k: v.tolist() for k, v in scores.items()}}


def main() -> None:
    OUT_ROOT.mkdir(parents=True, exist_ok=True)
    v2 = load_records(HORIZON_ROOT)
    v3 = load_records(V3_ROOT)
    if not v3:
        raise SystemExit("no v3 shards found -- run bg_v3_horizon_power_generate.py first")
    print(f"[v3-analysis] v2 records={len(v2)}  v3 records={len(v3)}")

    # --- Stage C1: disjointness + split integrity (prospective, deterministic).
    v2_tasks = {r["task_uid"] for r in v2}
    v3_tasks = {r["task_uid"] for r in v3}
    overlap = v2_tasks & v3_tasks
    assert not overlap, f"task overlap between v2 and v3 shards: {sorted(overlap)[:5]}"
    bad_split = [r["task_uid"] for r in v2 + v3 if r["split"] != split_for(r["task_uid"])]
    assert not bad_split, f"split mismatch vs deterministic split_for: {bad_split[:5]}"
    print(f"[v3-analysis] disjoint task sets OK ({len(v2_tasks)} v2, {len(v3_tasks)} v3); "
          "splits reproduce split_for exactly")

    # --- Stage A: exact reproduction gate on v2-only, 4-shortcut protocol. ----
    published = json.loads((HORIZON_ROOT / "auroc_results.json").read_text())
    gate, _ = run_arm("gate_v2_only_4sc", v2, shortcut_vec)
    for mine, theirs in [
        ("auroc_shortcut_only", published["heldout"]["auroc_shortcut_only"]),
        ("auroc_hidden_only", published["heldout"]["auroc_hidden_only"]),
        ("auroc_hidden_plus_shortcuts", published["heldout"]["auroc_hidden_plus_shortcuts"]),
        ("incremental_auroc_combined_minus_shortcut",
         published["heldout"]["incremental_auroc_combined_minus_shortcut"]),
    ]:
        if abs(gate[mine] - theirs) > GATE_TOL:
            raise SystemExit(f"STAGE A GATE FAILED: {mine} {gate[mine]!r} != published {theirs!r}")
    boot_pub = published["paired_task_clustered_bootstrap_combined_minus_shortcut"]
    if abs(gate["paired_task_clustered_bootstrap_combined_minus_shortcut"]["mean_delta"]
           - boot_pub["mean_delta"]) > GATE_TOL:
        raise SystemExit("STAGE A GATE FAILED: bootstrap mean_delta mismatch")
    print("[v3-analysis] STAGE A GATE PASSED: published v2 numbers reproduced to 1e-9")

    # --- Stage B: replication and pooled arms, both shortcut composites. ------
    pooled = v2 + v3
    mal_new = malformed_count_by_task(v3)
    mal_pool = malformed_count_by_task(pooled)
    results = {"stage_a_gate": "PASSED", "gate_arm": gate}
    preds = {}
    results["new_only_4sc"], preds["new_only_4sc"] = run_arm("new_only_4sc", v3, shortcut_vec)
    results["pooled_4sc"], preds["pooled_4sc"] = run_arm("pooled_4sc", pooled, shortcut_vec)
    results["new_only_5sc"], preds["new_only_5sc"] = run_arm(
        "new_only_5sc", v3, lambda r: shortcut_vec_aug(r, mal_new))
    results["pooled_5sc"], preds["pooled_5sc"] = run_arm(
        "pooled_5sc", pooled, lambda r: shortcut_vec_aug(r, mal_pool))

    # --- Stage C2: controls on the pooled 5-shortcut arm. ---------------------
    controls = {}
    scorable, Xhid, Xsc, y, tasks, tv, ho = assemble(
        pooled, lambda r: shortcut_vec_aug(r, mal_pool))
    tasks_tv = [t for t, m in zip(tasks, tv.tolist()) if m]
    tasks_ho = [t for t, m in zip(tasks, ho.tolist()) if m]

    # shuffled-label control
    y_ho = y[ho]
    perm = torch.randperm(y_ho.shape[0], generator=torch.Generator().manual_seed(SEED))
    s_comb = torch.tensor(preds["pooled_5sc"]["scores"]["combined"])
    controls["shuffled_label_auroc_combined"] = auroc(s_comb, y_ho[perm])

    # leave-one-task-out max influence on the pooled 5sc increment
    s_sc = torch.tensor(preds["pooled_5sc"]["scores"]["shortcut"])
    inc_full = results["pooled_5sc"]["incremental_auroc_combined_minus_shortcut"]
    max_dev, max_task = 0.0, None
    for t in sorted(set(tasks_ho)):
        keep = torch.tensor([tt != t for tt in tasks_ho])
        if keep.sum() < 10 or y_ho[keep].float().mean() in (0.0, 1.0):
            continue
        inc_t = auroc(s_comb[keep], y_ho[keep]) - auroc(s_sc[keep], y_ho[keep])
        if abs(inc_t - inc_full) > max_dev:
            max_dev, max_task = abs(inc_t - inc_full), t
    controls["loto_max_abs_influence"] = max_dev
    controls["loto_max_task"] = max_task

    # malformed-share task-drop recheck (threshold 0.75, as published)
    mal_share = {}
    for r in pooled:
        mal_share.setdefault(r["task_uid"], []).append(bool(r["malformed"]))
    heavy = {t for t, ms in mal_share.items() if sum(ms) / len(ms) >= 0.75}
    keep = torch.tensor([t not in heavy for t in tasks_ho])
    if keep.sum() >= 10 and y_ho[keep].float().mean() not in (0.0, 1.0):
        controls["drop_high_malformed_increment"] = (
            auroc(s_comb[keep], y_ho[keep]) - auroc(s_sc[keep], y_ho[keep]))
        controls["drop_high_malformed_n_tasks_dropped"] = len(heavy & set(tasks_ho))

    # descriptive: per-split composition
    for tag, recs in [("v2", v2), ("v3", v3), ("pooled", pooled)]:
        sc = [r for r in recs if not r["malformed"]]
        ho_sc = [r for r in sc if r["split"] == "heldout"]
        controls[f"{tag}_scorable"] = len(sc)
        controls[f"{tag}_heldout_scorable"] = len(ho_sc)
        controls[f"{tag}_heldout_negatives"] = sum(1 for r in ho_sc if not r["success"])
        controls[f"{tag}_malformed_rate"] = sum(r["malformed"] for r in recs) / len(recs)
    results["controls"] = controls

    # --- verdict ---------------------------------------------------------------
    n4 = results["new_only_4sc"]["paired_task_clustered_bootstrap_combined_minus_shortcut"]
    p4 = results["pooled_4sc"]["paired_task_clustered_bootstrap_combined_minus_shortcut"]
    n5 = results["new_only_5sc"]["paired_task_clustered_bootstrap_combined_minus_shortcut"]
    p5 = results["pooled_5sc"]["paired_task_clustered_bootstrap_combined_minus_shortcut"]
    if n5["excludes_zero"] and p5["excludes_zero"]:
        verdict = "REPLICATED_AND_ROBUST_TO_MALFORMED_SIBLING_SHORTCUT"
    elif p4["excludes_zero"] and not p5["excludes_zero"]:
        verdict = "REPLICATED_ON_PUBLISHED_PROTOCOL_BUT_NOT_ROBUST_TO_MALFORMED_SIBLING_SHORTCUT"
    elif not p4["excludes_zero"]:
        verdict = "DID_NOT_REPLICATE_AT_INCREASED_POWER"
    else:
        verdict = "MIXED_SEE_ARMS"
    results["verdict"] = verdict
    results["seed"] = SEED
    results["protocol"] = "identical to bg_v2_overnight_horizon_analysis + malformed_sibling_control"

    (OUT_ROOT / "auroc_results_v3.json").write_text(
        json.dumps(results, indent=2, default=str) + "\n")
    (OUT_ROOT / "raw_predictions_heldout_v3.json").write_text(
        json.dumps(preds, indent=2) + "\n")
    print(f"[v3-analysis] verdict: {verdict}")
    print(f"[v3-analysis] new-only 4sc: {n4['mean_delta']:+.4f} {n4['ci95']}")
    print(f"[v3-analysis] pooled  4sc: {p4['mean_delta']:+.4f} {p4['ci95']}")
    print(f"[v3-analysis] new-only 5sc: {n5['mean_delta']:+.4f} {n5['ci95']}")
    print(f"[v3-analysis] pooled  5sc: {p5['mean_delta']:+.4f} {p5['ci95']}")


if __name__ == "__main__":
    main()
